import { ipcRenderer } from 'electron'
import type {
  AgentDeskApi,
  MediaAdoptionInput,
  MediaApi,
  MediaAssetBindingInput,
  MediaAssetImportInput,
  MediaAssetPurgeInput,
  MediaAssetEgressInput,
  MediaAssetRetentionUpdateInput,
  MediaBudgetUpdateInput,
  MediaCharacterBibleDeleteInput,
  MediaCharacterBibleInput,
  MediaCompositionInput,
  MediaContinuityCheckInput,
  MediaContinuityLockDeleteInput,
  MediaContinuityLockInput,
  MediaDialogueCueDeleteInput,
  MediaDialogueCueInput,
  MediaJobInput,
  MediaProductionInput,
  MediaProductionRevisionInput,
  MediaProjectStorageUpdateInput,
  MediaProviderProfileDeleteInput,
  MediaProviderProfileInput,
  MediaShotInput,
  MediaShotUpdateInput,
  MediaTimelineUpdateInput
  , MediaVoiceCloneAuthorizationInput
} from '../shared/types'
const invoke = (action: string, ...args: unknown[]) => ipcRenderer.invoke('appFeatures:invoke', 'media', action, ...args)
export const mediaApi: Pick<AgentDeskApi, keyof MediaApi> = {
  getMediaStudio: (projectId?: string) => invoke('get', projectId),
  listMediaProviders: () => invoke('provider:list'),
  upsertMediaProvider: (input: MediaProviderProfileInput) => invoke('provider:upsert', input),
  deleteMediaProvider: (input: MediaProviderProfileDeleteInput) => invoke('provider:delete', input.id),
  getMediaFfmpegInfo: () => invoke('ffmpeg:get'),
  createVideoProduction: (input: MediaProductionInput) => invoke('production:create', input),
  reviseVideoProduction: (input: MediaProductionRevisionInput) => invoke('production:revise', input),
  addVideoShot: (input: MediaShotInput) => invoke('shot:create', input),
  updateVideoShot: (input: MediaShotUpdateInput) => invoke('shot:update', input),
  upsertMediaDialogueCue: (input: MediaDialogueCueInput) => invoke('dialogue:upsert', input),
  deleteMediaDialogueCue: (input: MediaDialogueCueDeleteInput) => invoke('dialogue:delete', input),
  updateMediaTimeline: (input: MediaTimelineUpdateInput) => invoke('timeline:update', input),
  updateMediaBudget: (input: MediaBudgetUpdateInput) => invoke('budget:update', input),
  updateMediaProjectStorage: (input: MediaProjectStorageUpdateInput) => invoke('storage:update', input),
  upsertMediaCharacterBible: (input: MediaCharacterBibleInput) => invoke('bible:upsert', input),
  deleteMediaCharacterBible: (input: MediaCharacterBibleDeleteInput) => invoke('bible:delete', input),
  upsertMediaContinuityLock: (input: MediaContinuityLockInput) => invoke('continuity-lock:upsert', input),
  deleteMediaContinuityLock: (input: MediaContinuityLockDeleteInput) => invoke('continuity-lock:delete', input),
  checkMediaContinuity: (input: MediaContinuityCheckInput) => invoke('continuity:check', input),
  importMediaAsset: (input: MediaAssetImportInput) => invoke('asset:import', input),
  bindMediaAsset: (input: MediaAssetBindingInput) => invoke('asset:bind', input),
  setMediaAdoption: (input: MediaAdoptionInput) => invoke('asset:adopt', input),
  updateMediaAssetRetention: (input: MediaAssetRetentionUpdateInput) => invoke('asset:retention', input),
  purgeMediaAsset: (input: MediaAssetPurgeInput) => invoke('asset:purge', input),
  setMediaAssetEgress: (input: MediaAssetEgressInput) => invoke('asset:egress', input),
  setMediaVoiceCloneAuthorization: (input: MediaVoiceCloneAuthorizationInput) => invoke('asset:voice-clone', input),
  composeMediaProduction: (input: MediaCompositionInput) => invoke('compose', input),
  submitMediaJob: (input: MediaJobInput) => invoke('job:submit', input),
  advanceMediaJob: (jobId: string) => invoke('job:advance', jobId),
  reconcileMediaJob: (jobId: string) => invoke('job:reconcile', jobId),
  cancelMediaJob: (jobId: string) => invoke('job:cancel', jobId)
}
