import type { HistoryEntry, SessionMeta } from '../shared/types'

/** Persist task ownership with its conversation, independent of the selected navigation tab. */
export function sessionHistoryEntry(meta: SessionMeta & { sdkSessionId: string }): HistoryEntry {
  return {
    id: meta.id,
    taskMemorySessionId: meta.taskMemorySessionId,
    title: meta.title,
    cwd: meta.cwd,
    driveMode: meta.driveMode,
    parentSessionId: meta.parentSessionId,
    orchestrationId: meta.orchestrationId,
    childTaskId: meta.childTaskId,
    childRole: meta.childRole,
    isolated: meta.isolated,
    sourceCwd: meta.sourceCwd,
    projectId: meta.projectId,
    workspaceId: meta.workspaceId,
    goalId: meta.goalId,
    workItemId: meta.workItemId, digitalWorkerBinding: meta.digitalWorkerBinding,
    unassigned: meta.unassigned,
    personalWorkspaceId: meta.personalWorkspaceId,
    businessLineId: meta.businessLineId,
    experienceModeOverride: meta.experienceModeOverride,
    repoRoot: meta.repoRoot,
    worktreePath: meta.worktreePath,
    branch: meta.branch,
    baseBranch: meta.baseBranch,
    baseSha: meta.baseSha,
    worktreeState: meta.worktreeState,
    model: meta.model,
    providerId: meta.providerId,
    routingScope: meta.routingScope,
    routingControl: meta.routingControl,
    modelRoutingDecision: meta.modelRoutingDecision,
    runtimeContinuation: meta.runtimeContinuation,
    modelChange: meta.modelChange,
    engine: meta.engine,
    executorEngine: meta.executorEngine,
    taskStrategy: meta.taskStrategy,
    taskExecutionAuthorityRequired: meta.taskExecutionAuthorityRequired,
    permissionMode: meta.permissionMode,
    sdkSessionId: meta.sdkSessionId,
    conversationForkSourceSdkSessionId: meta.conversationForkSourceSdkSessionId,
    conversationForkCheckpointId: meta.conversationForkCheckpointId,
    conversationForkSourceSessionId: meta.conversationForkSourceSessionId,
    conversationForkSourceRunId: meta.conversationForkSourceRunId,
    responsesContext: meta.responsesContext,
    createdAt: meta.createdAt,
    updatedAt: Date.now(),
    costUsd: meta.costUsd,
    budgetUsd: meta.budgetUsd,
    resumeSessionAt: meta.resumeSessionAt
  }
}
