import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { compileMission, missionCompilationToTaskPlanDraft } from '../src/main/task/mission-compiler'
import { TaskPlanContractStore } from '../src/main/task/task-plan-contract-store'
import { approvedTaskPlanToDag, taskDagToPlanDraft } from '../src/main/task/task-plan-dag'
import type { TaskDag, TaskPlanStepInput } from '../src/shared/types'

const root = mkdtempSync(path.join(tmpdir(), 'caogen-mission-role-contract-'))
const reportPath = path.resolve('test-results/mission-role-contract/latest.json')
const checks: { name: string; status: 'passed' | 'failed'; detail?: string }[] = []
const check = (name: string, run: () => void): void => {
  try { run(); checks.push({ name, status: 'passed' }) }
  catch (error) { checks.push({ name, status: 'failed', detail: String(error) }); throw error }
}
const store = new TaskPlanContractStore(() => root)
const file = path.join(root, 'task-plans/task-plan-contracts.json')
const legacySessionId = 'legacy-role-compat'
const draft = missionCompilationToTaskPlanDraft(compileMission({
  projectId: 'role-project', goalId: 'role-goal',
  objective: 'API UI 测试 发布 文档', deliverables: ['API UI 测试 发布 文档'],
  constraints: ['未经审批不得外发'], now: 1700000000000
}))

try {
  check('frozen pre-extension persisted plan and approval retain their original digest without rewriting', () => {
    // Generated by the actual store at commit 974aa2315a23a0b7bd9e8b4567d499421a1ea6a8,
    // before optional role/type/acceptance fields existed. Do not regenerate
    // this fixture with the current store: its old digest is the compatibility oracle.
    const fixture = readFileSync(path.resolve('scripts/fixtures/task-plan-legacy-v1.json'), 'utf8')
    mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 })
    writeFileSync(file, fixture, { mode: 0o600 })
    const legacy = store.get(legacySessionId)
    assert.equal(legacy.approvalStatus, 'approved')
    assert.equal(legacy.approvedDigest, 'sha256:e10bd6c165a4ff2099d1efecb689603150f9f2de61b81f4266d61d53774fc0c9')
    store.assertExecutionAuthorized(legacySessionId, true)
    for (const field of ['role', 'executionRole', 'workItemType', 'acceptanceSpec']) {
      assert.equal(Object.hasOwn(legacy.currentVersion!.steps[0], field), false)
    }
    assert.equal(readFileSync(file, 'utf8'), fixture)
  })
  check('legacy plans without structured execution roles retain the existing role fallback', () => {
    const legacy = store.get(legacySessionId)
    const dag = approvedTaskPlanToDag(legacySessionId, legacy.currentVersion!, legacy.projection)
    assert.equal(dag.tasks[0].role, 'qa')
    assert(!dag.tasks[0].prompt.includes('当前步骤验收条件'))
    assert(!dag.tasks[0].prompt.includes('岗位：'))
  })
  check('Mission execution roles and per-step acceptance survive conflicting words in shared objectives and titles', () => {
    const state = store.createVersion({ sessionId: 'structured-mission' }, draft, 'agent')
    const version = state.currentVersion!
    const dag = approvedTaskPlanToDag(state.sessionId, version)
    assert.deepEqual(dag.tasks.map((task) => task.role), ['general', 'general', 'docs', 'qa'])
    version.steps.forEach((step, index) => {
      assert(dag.tasks[index].prompt.includes(`岗位：${step.role}`))
      assert(dag.tasks[index].prompt.includes(`任务类型：${step.workItemType}`))
      for (const acceptance of step.acceptanceSpec!) {
        assert(dag.tasks[index].prompt.includes(`[${acceptance.id}] ${acceptance.criterion}（必需）`))
      }
    })
  })
  check('each new structured field is digest protected in persisted versions', () => {
    const original = readFileSync(file, 'utf8')
    const mutations: ((step: TaskPlanStepInput) => void)[] = [
      (step) => { step.role = 'review' },
      (step) => { step.executionRole = 'frontend' },
      (step) => { step.workItemType = 'testing' },
      (step) => { step.acceptanceSpec![0].criterion = 'forged acceptance' }
    ]
    try {
      for (const mutate of mutations) {
        const data = JSON.parse(original)
        mutate(data.sessions['structured-mission'].versions[0].steps[0])
        writeFileSync(file, JSON.stringify(data))
        assert.throws(() => new TaskPlanContractStore(() => root).get('structured-mission'), /摘要校验失败/)
      }
    } finally { writeFileSync(file, original) }
  })
  check('role, execution role, type and acceptance revisions each supersede prior approval', () => {
    const revisions: Partial<TaskPlanStepInput>[] = [
      { role: 'review' }, { executionRole: 'review' }, { workItemType: 'custom' },
      { acceptanceSpec: [{ id: 'review', criterion: 'Review final evidence', required: false }] }
    ]
    revisions.forEach((change, index) => {
      const binding = { sessionId: `role-revision-${index}` }
      const first = store.createVersion(binding, draft, 'local-user')
      store.approve(binding.sessionId, first.currentVersion!)
      const revised = store.createVersion(binding, {
        ...draft, changeReason: 'Change a structured execution requirement',
        steps: draft.steps.map((step, position) => position === 0 ? { ...step, ...change } : step)
      }, 'local-user')
      assert.notEqual(revised.currentVersion!.digest, first.currentVersion!.digest)
      assert.equal(revised.approvalStatus, 'pending')
      assert.equal(revised.approvalEvents.at(-1)?.kind, 'superseded')
      assert.throws(() => store.assertExecutionAuthorized(binding.sessionId, true), /尚未批准|执行授权/)
    })
  })
  check('invalid structured role, type and acceptance inputs fail closed', () => {
    const invalid: Partial<TaskPlanStepInput>[] = [
      { role: '' }, { role: null as never }, { executionRole: 'research' as never },
      { executionRole: { toString: () => 'general' } as never }, { workItemType: 'unknown' as never },
      { acceptanceSpec: [] },
      { acceptanceSpec: [{ id: 'same', criterion: 'first' }, { id: 'same', criterion: 'second' }] }
    ]
    invalid.forEach((change, index) => assert.throws(() => store.createVersion(
      { sessionId: `invalid-role-${index}` },
      { ...draft, steps: draft.steps.map((step, position) => position === 0 ? { ...step, ...change } : step) },
      'agent'
    )))
  })
  check('ordinary AI DAG plans preserve explicit runtime roles through a draft and stored version', () => {
    const dag: TaskDag = {
      id: 'existing-ai-dag', title: 'API UI 测试 发布 文档', source: 'Same misleading words in every title',
      complexity: 'multi', createdAt: 1700000000000,
      tasks: ['frontend', 'backend', 'qa', 'docs', 'devops', 'review', 'general'].map((role, index) => ({
        id: `task-${index}`, title: 'API UI 测试 发布 文档', description: 'API UI 测试 发布 文档',
        role: role as TaskDag['tasks'][number]['role'], dependencies: [], prompt: 'task'
      }))
    }
    const state = store.createVersion({ sessionId: 'ai-dag-role-roundtrip' }, taskDagToPlanDraft(dag), 'agent')
    const restored = approvedTaskPlanToDag(state.sessionId, state.currentVersion!)
    assert.deepEqual(restored.tasks.map((task) => task.role), dag.tasks.map((task) => task.role))
  })
} catch (error) {
  console.error(error)
  process.exitCode = 1
} finally {
  mkdirSync(path.dirname(reportPath), { recursive: true })
  const passed = checks.filter((entry) => entry.status === 'passed').length
  writeFileSync(reportPath, `${JSON.stringify({
    schemaVersion: 1, kind: 'caogen.mission-role-contract-report', status: process.exitCode ? 'failed' : 'passed',
    generatedAt: new Date().toISOString(), checks, summary: { passed, total: checks.length },
    limitations: ['local plan stores and DAG projection', 'no real Provider dispatch or human acceptance']
  }, null, 2)}\n`)
  rmSync(root, { recursive: true, force: true })
  console.log(`Mission role contract: ${passed}/${checks.length}; ${reportPath}`)
}
