import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compileMission } from '../src/main/task/mission-compiler'

const checks: { id: string; status: 'passed' | 'failed'; detail?: string }[] = []
const record = (id: string, detail: string, operation: () => void): void => { try { operation(); checks.push({ id, status: 'passed' }) } catch (error) { checks.push({ id, status: 'failed', detail: error instanceof Error ? error.message : String(error) }) } }
const input = { projectId: 'project-mission-contract', goalId: 'goal-mission-contract', objective: '本周形成可运行的产品发布包', constraints: ['未经批准不得外发', '每个成果必须可追溯'], deliverables: ['运行页面', '使用说明', 'Proof Pack'], materials: [{ id: 'brief', title: '脱敏需求' }, { id: 'brand', title: '品牌规则', uri: 'workspace://brand' }], now: 1700000000000 }
record('canonical-goal-and-business-line', '目标和业务线由同一编译结果生成并保持归属', () => { const result = compileMission(input); if (result.goal.projectId !== input.projectId || result.goal.status !== 'waiting_approval' || result.businessLine.name !== '产品发布府') throw new Error('canonical ownership/status mismatch') })
record('four-role-blueprint', '默认生成礼部、工部、文书和都察院四个角色', () => { const result = compileMission(input); if (result.roles.length !== 4 || result.workItems.length !== 4 || new Set(result.workItems.map((item) => item.role)).size !== 4) throw new Error('role blueprint incomplete') })
record('dag-dependencies', '工作项依赖形成无环 DAG', () => { const result = compileMission(input); const ids = new Set(result.workItems.map((item) => item.id)); if (result.dependencies.length !== 4 || result.dependencies.some((edge) => !ids.has(edge.fromWorkItemId) || !ids.has(edge.toWorkItemId))) throw new Error('dependency references invalid') })
record('acceptance-pending', '每个工作项创建 pending Acceptance 并绑定约束', () => { const result = compileMission(input); if (result.acceptances.length !== 4 || result.acceptances.some((item) => item.status !== 'pending' || item.criteria.length < 2 || item.workItemId === undefined)) throw new Error('acceptance blueprint incomplete') })
record('deterministic-digest', '输入材料顺序变化不改变编译摘要或身份', () => { const result = compileMission(input); const reordered = compileMission({ ...input, materials: [...input.materials].reverse() }); if (result.digest !== reordered.digest || JSON.stringify(result.workItems) !== JSON.stringify(reordered.workItems)) throw new Error('mission compilation is not deterministic') })
record('constraint-boundary', '空目标和空约束 fail-closed', () => { try { compileMission({ ...input, objective: '' }); throw new Error('empty objective accepted') } catch (error) { if (!String(error).includes('objective')) throw error } try { compileMission({ ...input, constraints: [] }); throw new Error('empty constraints accepted') } catch (error) { if (!String(error).includes('constraints')) throw error } })
record('material-integrity', '材料身份重复时 fail-closed', () => { try { compileMission({ ...input, materials: [{ id: 'brief', title: 'a' }, { id: 'brief', title: 'b' }] }); throw new Error('duplicate material accepted') } catch (error) { if (!String(error).includes('duplicate material')) throw error } })
record('digest-excludes-runtime-time', '运行时间不改变 mission digest', () => { const first = compileMission(input); const second = compileMission({ ...input, now: input.now + 999 }); if (first.digest !== second.digest) throw new Error('runtime timestamp leaked into digest') })
const failed = checks.filter((item) => item.status === 'failed')
const report = { schemaVersion: 1, contract: 'V2-002 Mission Compiler', status: failed.length ? 'failed' : 'passed', checks, summary: `${checks.length - failed.length}/${checks.length} checks passed`, generatedAt: new Date().toISOString() }
const output = resolve(process.cwd(), 'test-results/mission-compiler-contract/latest.json'); mkdirSync(resolve(output, '..'), { recursive: true }); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ ...report, reportPath: output }, null, 2)); if (failed.length) process.exitCode = 1
