import assert from 'node:assert/strict'
import { WorkspaceBrowserRegistry } from '../src/main/workspace-browser-context'

const contexts = new WorkspaceBrowserRegistry()
const first = contexts.acquire(1001, '/fixture/profile')
assert.match(first.id, /^workspace-browser:[a-f0-9-]{36}$/)
assert.equal(first.sourceKind, 'workspace_human')
assert.equal(contexts.acquire(1001, '/fixture/profile'), first)
const other = contexts.acquire(1002, '/fixture/profile')
assert.notEqual(first.id, other.id)
assert.equal(contexts.get(first.id, 1001), first)
assert.throws(() => contexts.get(first.id, 1002), /不属于/)
assert.equal(contexts.visible(first.id, 1001), true)
assert.equal(contexts.visible(first.id, 1002), false)
assert.equal(contexts.get('existing-task', 1001), undefined)
assert.equal(contexts.visible('existing-task', 1001), true)
assert.equal(contexts.visible(undefined, 1001), true)
assert.throws(() => contexts.get(undefined as unknown as string, 1001), /无效/)
assert.throws(() => contexts.get('', 1001), /无效/)
assert.throws(() => contexts.get('workspace-browser:forged', 1001), /不属于/)
assert.equal(contexts.release(1001), first.id)
assert.equal(contexts.visible(first.id, 1001), false)
assert.throws(() => contexts.get(first.id, 1001), /已经关闭/)
const reopened = contexts.acquire(1001, '/fixture/profile')
assert.notEqual(reopened.id, first.id)
assert.equal(contexts.get(other.id, 1002), other)
console.log('PASS: Independent browser identity, per-window ownership, cross-window rejection, lifecycle invalidation and unchanged task lookup semantics.')
