import { app } from 'electron'
import { createHash, randomUUID } from 'node:crypto'
import { getSettings } from '../settings'
import { getProvider, issueProviderCredentialLease, selectProviderCredential } from '../providers'
import { credentialFingerprint } from '../provider/providerCredentialIdentity'
import { readProviderConnectionIdentity } from '../provider/providerConnectionIdentity'
import { resolveProviderRuntimeTarget } from '../provider/providerRuntimeTarget'
import { inspectProviderBaseUrl, inspectProviderCustomHeaders } from '../providerCredentialBroker'
import { appendProviderRequestQuery } from '../provider/providerRequestOverrides'
import { parseProviderHeaders } from '../provider/openai-provider-utils'
import { assertRoutingExpertTargetAllowed } from '../model/routing-expert-policy'
import { fetchWithProviderCredentialLease } from '../providerRuntimeAuth'
import { nativeBudgetScope } from '../model/native-request-budget'
import { reserveRequestBudget, settleRequestBudget } from '../budget/request-budget-store'
import { sessionManager } from '../sessionManager'
import { createVoiceInputService, type VoiceTarget } from './service'
import { readVoiceTranscription, voiceTranscriptionEndpoint } from './transport'
import { saveVoiceInputUsage } from './usage'

function voiceTarget(): VoiceTarget {
  const settings = getSettings()
  const config = settings.voiceInput
  if (!config?.providerId || !config.model) throw new Error('请先在设置中选择语音转写厂商和模型。')
  const provider = getProvider(config.providerId)
  if (!provider || provider.engine !== 'openai') throw new Error('请选择支持 OpenAI 兼容语音转写接口的已保存厂商。')
  const target = resolveProviderRuntimeTarget(provider, { appId: 'voice-input', model: config.model })
  const checked = inspectProviderBaseUrl(target.baseUrl)
  if (checked.rejectedNames.length || !checked.safeValue) throw new Error('语音厂商网络地址无效。')
  const headers = inspectProviderCustomHeaders(provider.customHeaders ?? '')
  if (headers.rejectedNames.length) throw new Error('请先在厂商配置中迁移请求头中的凭据。')
  assertRoutingExpertTargetAllowed(provider.id, target.baseUrl, settings.routingExpertPolicy, target)
  const credential = selectProviderCredential(provider)
  if (provider.authMode !== 'none' && !credential.available) throw new Error('语音厂商没有可用密钥，请在设置中检查。')
  const identity = createHash('sha256').update(JSON.stringify({ identity: readProviderConnectionIdentity(provider), config,
    target, keyId: credential.keyId, routingPolicy: settings.routingExpertPolicy })).digest('hex')
  return { providerId: provider.id, providerName: provider.name, model: target.model, language: config.language,
    baseUrl: checked.safeValue, identity, keyId: credential.keyId, keyLabel: credential.keyId ? credentialFingerprint(provider.id, credential.keyId) : undefined }
}

export const voiceInputService = createVoiceInputService({
  target: voiceTarget,
  saveUsage: saveVoiceInputUsage,
  async execute(target, form, signal) {
    // Revalidate once more at the actual network boundary, after local accounting.
    if (voiceTarget().identity !== target.identity) throw new Error('语音连接已变更，未上传录音。')
    const provider = getProvider(target.providerId)!
    const scope = { providerId: provider.id, projectId: 'system:voice-input', sessionId: 'voice-input', operationId: randomUUID() }
    const selection = issueProviderCredentialLease(provider, scope, { ttlMs: 60_000 }, target.keyId)
    if (provider.authMode !== 'none' && (!selection.available || !selection.lease)) throw new Error('语音厂商凭据已不可用，未上传录音。')
    const url = appendProviderRequestQuery(voiceTranscriptionEndpoint(target.baseUrl), target.baseUrl, provider.advancedConfig?.request?.query)
    const headers: Record<string, string> = { accept: 'application/json', ...parseProviderHeaders(provider.customHeaders), ...(provider.advancedConfig?.request?.headers ?? {}) }
    // Multipart boundaries are generated by fetch, never inherited from text-provider headers.
    for (const key of Object.keys(headers)) if (['content-type', 'content-length', 'host'].includes(key.toLowerCase())) delete headers[key]
    let response: Response
    try {
      response = await fetchWithProviderCredentialLease({ provider, lease: selection.lease, scope, url,
        init: { method: 'POST', headers, body: form, signal, redirect: 'error' } })
    } catch {
      throw new Error('语音转写网络请求未完成，录音仍保留。已上传的请求可能计费，请手动决定是否重试。')
    }
    return readVoiceTranscription(response)
  },
  reserve(target, requestId, contextId) {
    const rootDir = app.getPath('userData')
    const provider = getProvider(target.providerId)!
    const currentSession = sessionManager.get(contextId)?.meta
    const meta = currentSession ?? { id: 'voice-input-drafts', providerId: target.providerId, createdAt: Date.now(), costUsd: 0 }
    const reservationId = `voice-input:${requestId}`
    const admission = reserveRequestBudget({ rootDir, id: reservationId, kind: 'media', providerId: target.providerId, model: target.model,
      scope: nativeBudgetScope(meta, { providerBudgetUsd: provider.budgetUsd }) })
    if (admission.reused) throw new Error('此语音请求已有用量记录，不能重复发送。')
    let sent = false
    return { sent: () => { sent = true }, finish: () => settleRequestBudget({ rootDir, id: reservationId,
      status: sent ? 'unknown' : 'released', ...(sent ? {} : { actualUsd: 0 }) }) }
  }
})
